### PR TITLE
Make return types from Constructor type procedures pointers as in C counterpart

### PR DESCRIPTION
**Pull request by ghost**
C functions like `ImColor_ImColor` or `ImVec2_ImVec2Float` did not have a return type previously because they're all constructors, and cimgui doesn't define a `ret` type for them in the `definitions.json`, so we must do that ourselves.

Basically checks if function is a constructor, and if it is, makes the return type a pointer to a type (which is the first part of the function name)

### CODE REVIEW

**Comment by ghost** [comment]
Before/after example
image

**Comment by ghost** [comment]
Actually I'm not sure if `ptr` is really neccessary here because even without it:
```nim
proc newImVec2*(x: float32, y: float32): ImVec2 {.importc: "ImVec2_ImVec2Float".}
```

stuff like 
```nim
    if igButton("Button", newImVec2(0, 0)):
      counter.inc
```
works, but I don't know low-level memory management well enough so maybe memory leaks in that case

In the cimgui though all of these return a pointer to a struct:
image

**Comment by lmariscal** [comment]
I have no clue why I wasn't notified 2 days ago or if it was opened 5 hrs ago, if the first is the case sorry for the delay.

Checking the other procedures that use this types I can see that they in fact require a `ptr` to the generated object. `IM_NEW` is actually a macro from [imgui.h#L1206](https://github.com/ocornut/imgui/blob/ecb9b1e2eba5becc38019b5c9f75fba711cd881b/imgui.h#L1206) seeing some lines above the macro declaration you can see that in fact the object is only being assigned but never freed. My assumption all this time has been that by having the data structure directly as a Nim object, it would be cleared by the Nim GC in due time, but being honest I have never really tested it out.

I think this PR could be a nice place to discuss memory management in NimGL. If this PR would be applied your previous code snippet would actually have to be[0] since the other case would leave the generated ImVec2 dangling.

[0]
```nim
var pos = newImVec2(0, 0)
if igButton("Button", pos[]):
  counter.inc
pos.igMemFree()
```

This leaves some options:
- Leave the code as it is and actually perform tests to verify that no memory is being kept uncheck
- Apply this PR as it is and make memory management manual and offer a helper type to help with this task
- Create our own constructors at generation time to follow a proper Nim data flow
- We could also see the viability of using our own alloc procs together with Nim's using `ImGui::SetAllocatorFunctions()`

Based on this selection I will be looking into also generating the proper procs for `ImVec2_ImVec2Float` and other alike.

Please let me know your thoughts.

Edit: Add another option

**Comment by lmariscal** [comment]
As a little side note I would like to hear your thoughts on the generator and if it was too convoluted. Thank you in advance!

If you are available in IRC you can find me in as lmariscal in the #nim channel at freenode. If that is the case I will later comment out a link to the log in this PR.

**Pull request closed without merging**
